import express, { type Express } from "express";
import cors from "cors";
import {
  modelRestEndpoints,
  addController,
  bearerTokenMiddleware,
  addContext,
  buildRoute,
  persistentDb,
  addSdkRoute,
} from "simply-served";
import { z } from "zod";
import { TodoDb } from "./types";

const app = express() as Express & { _meta: any[] };

app.use(express.json());
app.use(cors()); // Disable cors

type ServerCtx = {
  db: TodoDb;
  auth: {
    userId: string;
  };
};

app.use(addContext<ServerCtx>({ db: persistentDb() }));

app.use(bearerTokenMiddleware(""));

const userValidator = z.object({
  _id: z.uuid(),
  name: z.string(),
});
addController<ServerCtx>(app, {
  path: "/user",
  routes: modelRestEndpoints({
    validator: userValidator,
    collection: (db) => db.user,
    permissions: {
      create: { type: "publicAccess" },
      read: { type: "publicAccess" },
      modify: {
        type: "modelAuth",
        check: async ({ auth }) => ({ _id: { Equal: auth.userId } }),
      },
      delete: { type: "notAllowed" },
    },
  }),
});

const todoValidator = z.object({
  _id: z.uuid(),
  todoItem: z.string(),
  owner: z.uuid(),
  done: z.boolean().default(false),
});

addController<ServerCtx>(app, {
  path: "/todo",
  routes: {
    //  Autogenerated rest endpoints for the Todo model
    ...modelRestEndpoints({
      collection: (db) => db.todo,
      validator: todoValidator,
      permissions: {
        create: { type: "publicAccess" },
        read: { type: "publicAccess" },
        modify: { type: "publicAccess" },
        delete: { type: "publicAccess" },
      },
    }),
    // Custom route for getting the todos of the authenticated user
    myTodos: buildRoute<ServerCtx>("get")
      .path("/my-todos")
      .withAuth()
      .build(async (req, res, auth) => {
        const myTodos = await req.db.todo.findMany({
          condition: { owner: { Equal: auth.userId } },
        });
        return res.status(200).json(myTodos);
      }),
  },
});

// app.get("/", async (_req, res): Promise<any> => {
//   return res.status(200).json("Welcome to my server!");
// });
app.get("/:test", async (req, res): Promise<any> => {
  console.log(req.params.test);
  return res.status(200).json("Success");
});

addSdkRoute(app)

export { app };

if (require.main === module) {
  app.listen(8080, () => {
    console.info("Listening on port 8080\n");
    console.info(`Check out todo.html to interact with the server at:`);
    console.info(__dirname.split("src").at(0) + "frontend/todo.html");
  });
}
